/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algorithm;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author PC
 */
public class algorithm extends javax.swing.JFrame {
int xMouse;
int yMouse;
    /**
     * Creates new form algorithm
     */
    public algorithm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

     secondlist s = new secondlist();
     private static Vector <String> algorithm_image_name = new Vector<String>();
     private static Vector <String> algorithm_list = new Vector<String>(); 
      private static Vector <String> address_num = new Vector<String>(); 
    public void image_name (String main_image_name) {
        algorithm_image_name.addElement(main_image_name);
      
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        ㅡ1 = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        framedrag = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        map = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        priority_list_scroll = new javax.swing.JScrollPane();
        priority_list = new javax.swing.JList<>();
        plus = new javax.swing.JButton();
        back = new javax.swing.JButton();
        algorithm_update = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1252, 680));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1252, 680));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8);
        jPanel8.setBounds(0, 650, 1250, 30);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        ㅡ1.setBackground(new java.awt.Color(240, 233, 233));
        ㅡ1.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        ㅡ1.setForeground(new java.awt.Color(255, 255, 255));
        ㅡ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ㅡ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ㅡㅡㅡㅡ.gif"))); // NOI18N
        ㅡ1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ㅡ1MouseClicked(evt);
            }
        });

        x.setBackground(new java.awt.Color(240, 233, 233));
        x.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        x.setForeground(new java.awt.Color(255, 255, 255));
        x.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/xx.gif"))); // NOI18N
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(ㅡ1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(x)
                .addGap(31, 31, 31))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(x)
                    .addComponent(ㅡ1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(850, 0, 400, 70);

        framedrag.setBackground(new java.awt.Color(255, 204, 204));
        framedrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                framedragMouseDragged(evt);
            }
        });
        framedrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                framedragMousePressed(evt);
            }
        });
        jPanel1.add(framedrag);
        framedrag.setBounds(0, 0, 1250, 70);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        map.setBackground(new java.awt.Color(255, 255, 255));
        map.setForeground(new java.awt.Color(255, 255, 255));
        map.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        map.setMaximumSize(new java.awt.Dimension(700, 840));
        map.setMinimumSize(new java.awt.Dimension(700, 840));
        map.setLayout(null);
        jPanel2.add(map);
        map.setBounds(70, 50, 700, 550);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 850, 680);

        jPanel3.setBackground(new java.awt.Color(255, 233, 233));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        priority_list_scroll.setBorder(null);

        priority_list.setFont(new java.awt.Font("맑은 고딕 Semilight", 0, 24)); // NOI18N
        priority_list.setToolTipText("");
        priority_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                priority_listMouseClicked(evt);
            }
        });
        priority_list_scroll.setViewportView(priority_list);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(priority_list_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(priority_list_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 410, 560));

        plus.setBackground(new java.awt.Color(255, 255, 255));
        plus.setText("+");
        plus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusMouseClicked(evt);
            }
        });
        jPanel3.add(plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setText("뒤로가기 버튼");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel3.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        algorithm_update.setBackground(new java.awt.Color(255, 255, 255));
        algorithm_update.setText("update");
        algorithm_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                algorithm_updateMouseClicked(evt);
            }
        });
        algorithm_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algorithm_updateActionPerformed(evt);
            }
        });
        jPanel3.add(algorithm_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 80, -1));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(850, 70, 400, 610);

        jPanel6.setBackground(new java.awt.Color(255, 233, 233));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 0, 51, 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1252, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1252, 680));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
  
  public void add_algorithm_list (String str) {
      algorithm_list.addElement(str);
     for(int i=0; i<algorithm_list.size();i++) {    ;
       System.out.println(algorithm_list.elementAt(i));
        }
  }
   public void file_address(String addr) {
     address_num.addElement(addr);
        System.out.println(address_num.elementAt(0));
    }
   DefaultListModel m = new DefaultListModel();
    private void priority_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_priority_listMouseClicked
     
       
        
    }//GEN-LAST:event_priority_listMouseClicked

    
    
    private void plusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusMouseClicked
        
        String data = priority_list.getSelectedValue().toString();
        s.add_list(data);
        
        
    }//GEN-LAST:event_plusMouseClicked
// + 버튼을 누르면 secondlist class의 vector에 추가 된다
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        algorithm_list.removeAllElements();
        address_num.removeAllElements();
        main main2 = new main();
         main2.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void algorithm_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algorithm_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_algorithm_updateActionPerformed

    
    
    public static JLabel la1 = null;
    public static JLabel la2 = null;
    public static JLabel la3 = null;
    public static JLabel la4 = null;
    public static JLabel la5 = null;
    public static JLabel la6= null;
    public static JLabel la7 =  null;
    public static JLabel la8 = null;
    public static JLabel la9 = null;
    public static JLabel la10 =null;
    
    
   
    private void algorithm_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_algorithm_updateMouseClicked
 
        priority_list.setListData(algorithm_list); 
        ImageIcon icon;
        String image_name = algorithm_image_name.elementAt(0);
        icon = new ImageIcon(getClass().getResource(image_name));
        Image img = icon.getImage();
        Graphics g = map.getGraphics();
       
        g.drawImage(img,map.getWidth()/5,map.getHeight()/8,icon.getIconWidth(), icon.getIconHeight(), map);
     System.out.println(image_name);
        algorithm_image_name.removeAllElements();

        
        
    }//GEN-LAST:event_algorithm_updateMouseClicked

    private void ㅡ1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ㅡ1MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_ㅡ1MouseClicked

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        System.exit(0);
    }//GEN-LAST:event_xMouseClicked

    private void framedragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedragMouseDragged
        int x = evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_framedragMouseDragged

    private void framedragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedragMousePressed
        xMouse = evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_framedragMousePressed
  
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
           
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(algorithm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(algorithm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(algorithm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(algorithm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new algorithm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton algorithm_update;
    private javax.swing.JButton back;
    private javax.swing.JLabel framedrag;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel map;
    private javax.swing.JButton plus;
    private javax.swing.JList<String> priority_list;
    private javax.swing.JScrollPane priority_list_scroll;
    private javax.swing.JLabel x;
    private javax.swing.JLabel ㅡ1;
    // End of variables declaration//GEN-END:variables

    void setIcon(ImageIcon i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
