/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algorithm;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author LG
 */
public class main extends javax.swing.JFrame {
int xMouse;
int yMouse;
 ImageIcon i;
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        x = new javax.swing.JLabel();
        ㅡ1 = new javax.swing.JLabel();
        framedrag = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        강서 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        양천 = new javax.swing.JLabel();
        구로 = new javax.swing.JLabel();
        영등포 = new javax.swing.JLabel();
        마포 = new javax.swing.JLabel();
        금천 = new javax.swing.JLabel();
        은평 = new javax.swing.JLabel();
        서대문 = new javax.swing.JLabel();
        종로 = new javax.swing.JLabel();
        중 = new javax.swing.JLabel();
        용산 = new javax.swing.JLabel();
        동작 = new javax.swing.JLabel();
        서초 = new javax.swing.JLabel();
        관악 = new javax.swing.JLabel();
        강남 = new javax.swing.JLabel();
        송파 = new javax.swing.JLabel();
        강동 = new javax.swing.JLabel();
        광진 = new javax.swing.JLabel();
        중랑 = new javax.swing.JLabel();
        노원 = new javax.swing.JLabel();
        강북 = new javax.swing.JLabel();
        성북 = new javax.swing.JLabel();
        동대문 = new javax.swing.JLabel();
        도봉 = new javax.swing.JLabel();
        성동 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        framedrag1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        framedrag2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        x.setBackground(new java.awt.Color(240, 233, 233));
        x.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        x.setForeground(new java.awt.Color(255, 255, 255));
        x.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/xx.gif"))); // NOI18N
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
        });
        jPanel2.add(x);
        x.setBounds(1220, 10, 52, 52);

        ㅡ1.setBackground(new java.awt.Color(240, 233, 233));
        ㅡ1.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        ㅡ1.setForeground(new java.awt.Color(255, 255, 255));
        ㅡ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ㅡ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ㅡㅡㅡㅡ.gif"))); // NOI18N
        ㅡ1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ㅡ1MouseClicked(evt);
            }
        });
        jPanel2.add(ㅡ1);
        ㅡ1.setBounds(1160, 10, 52, 52);

        framedrag.setBackground(new java.awt.Color(255, 204, 204));
        framedrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                framedragMouseDragged(evt);
            }
        });
        framedrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                framedragMousePressed(evt);
            }
        });
        jPanel2.add(framedrag);
        framedrag.setBounds(0, -10, 1340, 80);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 10, 1340, 70);

        jPanel1.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        강서.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        강서.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1.png"))); // NOI18N
        강서.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        강서.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                강서MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                강서MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                강서MouseExited(evt);
            }
        });
        jPanel5.add(강서);
        강서.setBounds(370, 270, 260, 200);

        jPanel4.setBackground(new java.awt.Color(231, 205, 215));
        jPanel4.setForeground(new java.awt.Color(231, 194, 209));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("HELP");
        jPanel4.add(jLabel4);

        jPanel5.add(jPanel4);
        jPanel4.setBounds(140, 710, 110, 30);

        양천.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/18.png"))); // NOI18N
        양천.setText("jLabel2");
        양천.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        양천.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                양천MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                양천MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                양천MouseExited(evt);
            }
        });
        jPanel5.add(양천);
        양천.setBounds(480, 410, 140, 110);

        구로.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        구로.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/7.png"))); // NOI18N
        구로.setText("jLabel3");
        구로.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        구로.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        구로.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                구로MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                구로MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                구로MouseExited(evt);
            }
        });
        jPanel5.add(구로);
        구로.setBounds(470, 470, 200, 140);

        영등포.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/19.png"))); // NOI18N
        영등포.setText("jLabel4");
        영등포.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        영등포.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                영등포MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                영등포MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                영등포MouseExited(evt);
            }
        });
        jPanel5.add(영등포);
        영등포.setBounds(590, 400, 170, 170);

        마포.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/13.png"))); // NOI18N
        마포.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        마포.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                마포MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                마포MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                마포MouseExited(evt);
            }
        });
        jPanel5.add(마포);
        마포.setBounds(560, 300, 220, 170);

        금천.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        금천.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/8.png"))); // NOI18N
        금천.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        금천.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                금천MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                금천MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                금천MouseExited(evt);
            }
        });
        jPanel5.add(금천);
        금천.setBounds(590, 550, 120, 160);

        은평.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        은평.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/21.png"))); // NOI18N
        은평.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        은평.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                은평MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                은평MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                은평MouseExited(evt);
            }
        });
        jPanel5.add(은평);
        은평.setBounds(620, 130, 175, 220);

        서대문.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        서대문.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/14.png"))); // NOI18N
        서대문.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        서대문.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                서대문MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                서대문MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                서대문MouseExited(evt);
            }
        });
        jPanel5.add(서대문);
        서대문.setBounds(650, 260, 150, 140);

        종로.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/22.png"))); // NOI18N
        종로.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        종로.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                종로MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                종로MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                종로MouseExited(evt);
            }
        });
        jPanel5.add(종로);
        종로.setBounds(750, 190, 160, 180);

        중.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/23.png"))); // NOI18N
        중.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        중.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                중MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                중MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                중MouseExited(evt);
            }
        });
        jPanel5.add(중);
        중.setBounds(770, 350, 140, 80);

        용산.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        용산.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/20.png"))); // NOI18N
        용산.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        용산.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                용산MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                용산MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                용산MouseExited(evt);
            }
        });
        jPanel5.add(용산);
        용산.setBounds(740, 400, 160, 110);

        동작.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        동작.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/12.png"))); // NOI18N
        동작.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        동작.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                동작MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                동작MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                동작MouseExited(evt);
            }
        });
        jPanel5.add(동작);
        동작.setBounds(650, 480, 190, 120);

        서초.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/15.png"))); // NOI18N
        서초.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        서초.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                서초MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                서초MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                서초MouseExited(evt);
            }
        });
        jPanel5.add(서초);
        서초.setBounds(810, 470, 250, 250);

        관악.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/5.png"))); // NOI18N
        관악.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        관악.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                관악MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                관악MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                관악MouseExited(evt);
            }
        });
        jPanel5.add(관악);
        관악.setBounds(650, 550, 190, 150);

        강남.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/2.png"))); // NOI18N
        강남.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        강남.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                강남MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                강남MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                강남MouseExited(evt);
            }
        });
        jPanel5.add(강남);
        강남.setBounds(880, 430, 240, 220);

        송파.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        송파.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/17.png"))); // NOI18N
        송파.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        송파.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                송파MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                송파MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                송파MouseExited(evt);
            }
        });
        jPanel5.add(송파);
        송파.setBounds(990, 420, 200, 200);

        강동.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        강동.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/3.png"))); // NOI18N
        강동.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        강동.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                강동MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                강동MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                강동MouseExited(evt);
            }
        });
        jPanel5.add(강동);
        강동.setBounds(1070, 320, 160, 180);

        광진.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        광진.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/6.png"))); // NOI18N
        광진.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        광진.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                광진MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                광진MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                광진MouseExited(evt);
            }
        });
        jPanel5.add(광진);
        광진.setBounds(970, 350, 121, 129);

        중랑.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24.png"))); // NOI18N
        중랑.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        중랑.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                중랑MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                중랑MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                중랑MouseExited(evt);
            }
        });
        jPanel5.add(중랑);
        중랑.setBounds(990, 230, 110, 140);

        노원.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        노원.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/9.png"))); // NOI18N
        노원.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        노원.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                노원MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                노원MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                노원MouseExited(evt);
            }
        });
        jPanel5.add(노원);
        노원.setBounds(940, 30, 150, 230);

        강북.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/4.png"))); // NOI18N
        강북.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        강북.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                강북MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                강북MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                강북MouseExited(evt);
            }
        });
        jPanel5.add(강북);
        강북.setBounds(810, 60, 160, 195);

        성북.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16.png"))); // NOI18N
        성북.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        성북.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                성북MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                성북MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                성북MouseExited(evt);
            }
        });
        jPanel5.add(성북);
        성북.setBounds(800, 180, 210, 160);

        동대문.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        동대문.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/11.png"))); // NOI18N
        동대문.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        동대문.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                동대문MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                동대문MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                동대문MouseExited(evt);
            }
        });
        jPanel5.add(동대문);
        동대문.setBounds(900, 260, 120, 130);

        도봉.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        도봉.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/10.png"))); // NOI18N
        도봉.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        도봉.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                도봉MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                도봉MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                도봉MouseExited(evt);
            }
        });
        jPanel5.add(도봉);
        도봉.setBounds(860, 10, 120, 210);

        성동.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/25.png"))); // NOI18N
        성동.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        성동.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                성동MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                성동MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                성동MouseExited(evt);
            }
        });
        jPanel5.add(성동);
        성동.setBounds(880, 350, 130, 110);

        jPanel6.setBackground(new java.awt.Color(255, 242, 242));
        jPanel6.setLayout(null);
        jPanel5.add(jPanel6);
        jPanel6.setBounds(0, 160, 1340, 390);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setLayout(null);

        framedrag1.setBackground(new java.awt.Color(255, 204, 204));
        framedrag1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                framedrag1MouseDragged(evt);
            }
        });
        framedrag1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                framedrag1MousePressed(evt);
            }
        });
        jPanel7.add(framedrag1);
        framedrag1.setBounds(0, 30, 1340, 50);

        jPanel5.add(jPanel7);
        jPanel7.setBounds(0, 750, 1340, 30);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setText("Select the area you want to go to.");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(110, 40, 420, 40);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/빨간하트.gif"))); // NOI18N
        jLabel3.setText("jLabel1");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(60, 20, 70, 50);
        jPanel5.add(jSeparator1);
        jSeparator1.setBounds(0, 80, 480, 20);

        jPanel3.setBackground(new java.awt.Color(231, 205, 215));
        jPanel3.setForeground(new java.awt.Color(231, 194, 209));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LOGOUT");
        jPanel3.add(jLabel5);

        jPanel5.add(jPanel3);
        jPanel3.setBounds(20, 710, 110, 30);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 80, 1340, 790);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setLayout(null);

        framedrag2.setBackground(new java.awt.Color(255, 204, 204));
        framedrag2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                framedrag2MouseDragged(evt);
            }
        });
        framedrag2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                framedrag2MousePressed(evt);
            }
        });
        jPanel8.add(framedrag2);
        framedrag2.setBounds(0, 0, 1340, 80);

        jPanel1.add(jPanel8);
        jPanel8.setBounds(0, 0, 1340, 10);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1340, 860);

        setSize(new java.awt.Dimension(1341, 857));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void framedragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedragMousePressed
          xMouse = evt.getX();
       yMouse=evt.getY();
    }//GEN-LAST:event_framedragMousePressed

    private void framedragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedragMouseDragged
       int x = evt.getXOnScreen();
        int y= evt.getYOnScreen();
       this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_framedragMouseDragged

    private void 성동MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_성동MouseExited
        i=new ImageIcon(getClass().getResource("/icons/25.png"));
        성동.setIcon(i);
    }//GEN-LAST:event_성동MouseExited

    private void 성동MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_성동MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/25_25.png"));
        성동.setIcon(i);
    }//GEN-LAST:event_성동MouseEntered

    private void 성동MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_성동MouseClicked
        String filename = "textfile/25.txt";
        algorithm.image_name("/icons/21_21.png");
        click_map(filename);
    }//GEN-LAST:event_성동MouseClicked

    private void 도봉MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_도봉MouseExited
        i=new ImageIcon(getClass().getResource("/icons/10.png"));
        도봉.setIcon(i);
    }//GEN-LAST:event_도봉MouseExited

    private void 도봉MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_도봉MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/10_10.png"));
        도봉.setIcon(i);
    }//GEN-LAST:event_도봉MouseEntered

    private void 도봉MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_도봉MouseClicked
        String filename = "textfile/10.txt";
        algorithm.image_name("/icons/10.png");
        click_map(filename);
    }//GEN-LAST:event_도봉MouseClicked

    private void 동대문MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_동대문MouseExited
        i=new ImageIcon(getClass().getResource("/icons/11.png"));
        동대문.setIcon(i);
    }//GEN-LAST:event_동대문MouseExited

    private void 동대문MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_동대문MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/11_11.png"));
        동대문.setIcon(i);
    }//GEN-LAST:event_동대문MouseEntered

    private void 동대문MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_동대문MouseClicked
        String filename = "textfile/11.txt";
        algorithm.image_name("/icons/11.png");
        click_map(filename);
    }//GEN-LAST:event_동대문MouseClicked

    private void 성북MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_성북MouseExited
        i=new ImageIcon(getClass().getResource("/icons/16.png"));
        성북.setIcon(i);
    }//GEN-LAST:event_성북MouseExited

    private void 성북MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_성북MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/16_16.png"));
        성북.setIcon(i);
    }//GEN-LAST:event_성북MouseEntered

    private void 성북MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_성북MouseClicked
        String filename = "textfile/16.txt";
        algorithm.image_name("/icons/16_16.png");
        click_map(filename);
    }//GEN-LAST:event_성북MouseClicked

    private void 강북MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_강북MouseExited
        i=new ImageIcon(getClass().getResource("/icons/4.png"));
        강북.setIcon(i);
    }//GEN-LAST:event_강북MouseExited

    private void 강북MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_강북MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/4_4.png"));
        강북.setIcon(i);
    }//GEN-LAST:event_강북MouseEntered

    private void 강북MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_강북MouseClicked
        String filename = "textfile/4.txt";
        algorithm.image_name("/icons/4.png");
        click_map(filename);
    }//GEN-LAST:event_강북MouseClicked

    private void 노원MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_노원MouseExited
        i=new ImageIcon(getClass().getResource("/icons/9.png"));
        노원.setIcon(i);
    }//GEN-LAST:event_노원MouseExited

    private void 노원MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_노원MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/9_9.png"));
        노원.setIcon(i);
    }//GEN-LAST:event_노원MouseEntered

    private void 노원MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_노원MouseClicked
        String filename = "textfile/9.txt";
        algorithm.image_name("/icons/24.png");
        click_map(filename);
    }//GEN-LAST:event_노원MouseClicked

    private void 중랑MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_중랑MouseExited
        i=new ImageIcon(getClass().getResource("/icons/24.png"));
        중랑.setIcon(i);
    }//GEN-LAST:event_중랑MouseExited

    private void 중랑MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_중랑MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/24_24.png"));
        중랑.setIcon(i);
    }//GEN-LAST:event_중랑MouseEntered

    private void 중랑MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_중랑MouseClicked
        String filename = "textfile/24.txt";
        algorithm.image_name("/icons/24.png");
        click_map(filename);
    }//GEN-LAST:event_중랑MouseClicked

    private void 광진MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_광진MouseExited
        i=new ImageIcon(getClass().getResource("/icons/6.png"));
        광진.setIcon(i);
    }//GEN-LAST:event_광진MouseExited

    private void 광진MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_광진MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/6_6.png"));
        광진.setIcon(i);
    }//GEN-LAST:event_광진MouseEntered

    private void 광진MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_광진MouseClicked
        String filename = "textfile/kwangjingu.txt";
        algorithm.image_name("/icons/gwanggin.png");
        algorithm.file_address("6");
        click_map(filename);
    }//GEN-LAST:event_광진MouseClicked

    private void 강동MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_강동MouseExited
        i=new ImageIcon(getClass().getResource("/icons/3.png"));
        강동.setIcon(i);
    }//GEN-LAST:event_강동MouseExited

    private void 강동MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_강동MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/3_3.png"));
        강동.setIcon(i);
    }//GEN-LAST:event_강동MouseEntered

    private void 강동MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_강동MouseClicked
        String filename = "textfile/3.txt";
        algorithm.image_name("/icons/3.png");
        click_map(filename);
    }//GEN-LAST:event_강동MouseClicked

    private void 송파MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_송파MouseExited
        i=new ImageIcon(getClass().getResource("/icons/17.png"));
        송파.setIcon(i);
    }//GEN-LAST:event_송파MouseExited

    private void 송파MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_송파MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/17_17.png"));
        송파.setIcon(i);
    }//GEN-LAST:event_송파MouseEntered

    private void 송파MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_송파MouseClicked
        String filename = "textfile/songpagu.txt";
        algorithm.image_name("/icons/songpa.png");
        click_map(filename);
        algorithm.file_address("17");
    }//GEN-LAST:event_송파MouseClicked

    private void 강남MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_강남MouseExited
        i=new ImageIcon(getClass().getResource("/icons/2.png"));
        강남.setIcon(i);
    }//GEN-LAST:event_강남MouseExited

    private void 강남MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_강남MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/2_2.png"));
        강남.setIcon(i);
    }//GEN-LAST:event_강남MouseEntered

    private void 강남MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_강남MouseClicked
        String filename = "textfile/gangnamgu.txt";
        algorithm.image_name("/icons/gangnam.png");
        click_map(filename);
        algorithm.file_address("2");
    }//GEN-LAST:event_강남MouseClicked

    private void 관악MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_관악MouseExited
        i=new ImageIcon(getClass().getResource("/icons/5.png"));
        관악.setIcon(i);
    }//GEN-LAST:event_관악MouseExited

    private void 관악MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_관악MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/5_5.png"));
        관악.setIcon(i);
    }//GEN-LAST:event_관악MouseEntered

    private void 관악MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_관악MouseClicked
        String filename = "textfile/5.txt";
        algorithm.image_name("/icons/5.png");
        click_map(filename);
    }//GEN-LAST:event_관악MouseClicked

    private void 서초MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_서초MouseExited
        i=new ImageIcon(getClass().getResource("/icons/15.png"));
        서초.setIcon(i);
    }//GEN-LAST:event_서초MouseExited

    private void 서초MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_서초MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/15_15.png"));
        서초.setIcon(i);
    }//GEN-LAST:event_서초MouseEntered

    private void 서초MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_서초MouseClicked
        String filename = "textfile/15.txt";
        algorithm.image_name("/icons/21_21.png");
        click_map(filename);
    }//GEN-LAST:event_서초MouseClicked

    private void 동작MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_동작MouseExited
        // TODO add your handling code here:
        i=new ImageIcon(getClass().getResource("/icons/12.png"));
        동작.setIcon(i);
    }//GEN-LAST:event_동작MouseExited

    private void 동작MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_동작MouseEntered
        // TODO add your handling code here:
        i=new ImageIcon(getClass().getResource("/icons/12_12.png"));
        동작.setIcon(i);
    }//GEN-LAST:event_동작MouseEntered

    private void 동작MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_동작MouseClicked
        String filename = "textfile/12.txt";
        algorithm.image_name("/icons/12.png");
        click_map(filename);
    }//GEN-LAST:event_동작MouseClicked

    private void 용산MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_용산MouseExited
        i=new ImageIcon(getClass().getResource("/icons/20.png"));
        용산.setIcon(i);
    }//GEN-LAST:event_용산MouseExited

    private void 용산MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_용산MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/20_20.png"));
        용산.setIcon(i);
    }//GEN-LAST:event_용산MouseEntered

    private void 용산MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_용산MouseClicked
        String filename = "textfile/20.txt";
        algorithm.image_name("/icons/20.png");
        click_map(filename);
    }//GEN-LAST:event_용산MouseClicked

    private void 중MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_중MouseExited
        i=new ImageIcon(getClass().getResource("/icons/23.png"));
        중.setIcon(i);
    }//GEN-LAST:event_중MouseExited

    private void 중MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_중MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/23_23.png"));
        중.setIcon(i);
    }//GEN-LAST:event_중MouseEntered

    private void 중MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_중MouseClicked
        String filename = "textfile/23.txt";
        algorithm.image_name("/icons/23.png");
        click_map(filename);
    }//GEN-LAST:event_중MouseClicked

    private void 종로MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_종로MouseExited
        // TODO add your handling code here:
        i=new ImageIcon(getClass().getResource("/icons/22.png"));
        종로.setIcon(i);
    }//GEN-LAST:event_종로MouseExited

    private void 종로MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_종로MouseEntered
        // TODO add your handling code here:
        i=new ImageIcon(getClass().getResource("/icons/22_22.png"));
        종로.setIcon(i);
    }//GEN-LAST:event_종로MouseEntered

    private void 종로MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_종로MouseClicked
        String filename = "textfile/22.txt";
        algorithm.image_name("/icons/22.png");
        click_map(filename);
    }//GEN-LAST:event_종로MouseClicked

    private void 서대문MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_서대문MouseExited
        i=new ImageIcon(getClass().getResource("/icons/14.png"));
        서대문.setIcon(i);
    }//GEN-LAST:event_서대문MouseExited

    private void 서대문MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_서대문MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/14_14.png"));
        서대문.setIcon(i);
    }//GEN-LAST:event_서대문MouseEntered

    private void 서대문MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_서대문MouseClicked
        String filename = "textfile/14.txt";
        algorithm.image_name("/icons/14.png");
        click_map(filename);
    }//GEN-LAST:event_서대문MouseClicked

    private void 은평MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_은평MouseExited
        i=new ImageIcon(getClass().getResource("/icons/21.png"));
        은평.setIcon(i);
    }//GEN-LAST:event_은평MouseExited

    private void 은평MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_은평MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/21_21_2.png"));
        은평.setIcon(i);
    }//GEN-LAST:event_은평MouseEntered

    private void 은평MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_은평MouseClicked
        String filename = "textfile/21.txt";
        algorithm.image_name("/icons/21_21_1.png");
        click_map(filename);
    }//GEN-LAST:event_은평MouseClicked

    private void 금천MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_금천MouseExited
        i=new ImageIcon(getClass().getResource("/icons/8.png"));
        금천.setIcon(i);
    }//GEN-LAST:event_금천MouseExited

    private void 금천MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_금천MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/8_8.png"));
        금천.setIcon(i);
    }//GEN-LAST:event_금천MouseEntered

    private void 금천MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_금천MouseClicked
        String filename = "textfile/8.txt";
        algorithm.image_name("/icons/8.png");
        click_map(filename);
    }//GEN-LAST:event_금천MouseClicked

    private void 마포MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_마포MouseExited
        i=new ImageIcon(getClass().getResource("/icons/13.png"));
        마포.setIcon(i);
    }//GEN-LAST:event_마포MouseExited

    private void 마포MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_마포MouseEntered
        // TODO add your handling code here:
        i=new ImageIcon(getClass().getResource("/icons/13_13.png"));
        마포.setIcon(i);
    }//GEN-LAST:event_마포MouseEntered

    private void 마포MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_마포MouseClicked
        String filename = "textfile/13.txt";
        algorithm.image_name("/icons/13.png");
        click_map(filename);
    }//GEN-LAST:event_마포MouseClicked

    private void 영등포MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_영등포MouseExited
        i=new ImageIcon(getClass().getResource("/icons/19.png"));
        영등포.setIcon(i);
    }//GEN-LAST:event_영등포MouseExited

    private void 영등포MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_영등포MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/19_19.png"));
        영등포.setIcon(i);
    }//GEN-LAST:event_영등포MouseEntered

    private void 영등포MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_영등포MouseClicked
        String filename = "textfile/19.txt";
        algorithm.image_name("/icons/19.png");
        click_map(filename);
    }//GEN-LAST:event_영등포MouseClicked

    private void 구로MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_구로MouseExited
        i=new ImageIcon(getClass().getResource("/icons/7.png"));
        구로.setIcon(i);
    }//GEN-LAST:event_구로MouseExited

    private void 구로MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_구로MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/7_7.png"));
        구로.setIcon(i);
    }//GEN-LAST:event_구로MouseEntered

    private void 구로MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_구로MouseClicked
        String filename = "textfile/7.txt";
        algorithm.image_name("/icons/7.png");
        click_map(filename);
    }//GEN-LAST:event_구로MouseClicked

    private void 양천MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_양천MouseExited
        i=new ImageIcon(getClass().getResource("/icons/18.png"));
        양천.setIcon(i);
    }//GEN-LAST:event_양천MouseExited

    private void 양천MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_양천MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/18_18.png"));
        양천.setIcon(i);
    }//GEN-LAST:event_양천MouseEntered

    private void 양천MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_양천MouseClicked
        String filename = "textfile/18.txt";
        algorithm.image_name("/icons/18.png");
        click_map(filename);
    }//GEN-LAST:event_양천MouseClicked

    private void 강서MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_강서MouseExited
        i=new ImageIcon(getClass().getResource("/icons/1.png"));
        강서.setIcon(i);
    }//GEN-LAST:event_강서MouseExited

    private void 강서MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_강서MouseEntered
        i=new ImageIcon(getClass().getResource("/icons/1_1.png"));
        강서.setIcon(i);
    }//GEN-LAST:event_강서MouseEntered

    private void 강서MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_강서MouseClicked
        String filename = "textfile/1.txt";
        algorithm.image_name("/icons/1.png");
        click_map(filename);
    }//GEN-LAST:event_강서MouseClicked

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        System.exit(0);  
    }//GEN-LAST:event_xMouseClicked

    private void ㅡ1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ㅡ1MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_ㅡ1MouseClicked

    private void framedrag1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedrag1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_framedrag1MouseDragged

    private void framedrag1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedrag1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_framedrag1MousePressed

    private void framedrag2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedrag2MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_framedrag2MouseDragged

    private void framedrag2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedrag2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_framedrag2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }
algorithm algorithm = new algorithm();
    
    secondlist s = new secondlist();
    
    /**
     * @param args the command line arguments
     */
    
   
    public void click_map(String filename) {
         File file;
     file = new File(filename);
    int count = 0;
     try {
            FileReader filereader = new FileReader(file);
           BufferedReader bufReader = new BufferedReader(filereader);
            String tmp = bufReader.readLine();
            String line = "";
            while((line = bufReader.readLine())!= null) {
             StringTokenizer st = new StringTokenizer(line, "_");
             while(st.hasMoreTokens()) {
                 
                 if(count == 3) break;
                
                 String temp = st.nextToken();
                 System.out.println(temp);
                  if(count ==0) {
                    algorithm.add_algorithm_list(temp); 
                 }
                 count ++;
             }
                
                count = 0;
                     
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        
    
     algorithm.setVisible(true);
      this.setVisible(false);
     algorithm.pack();
     algorithm.setDefaultCloseOperation(main.EXIT_ON_CLOSE);
     this.dispose();
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel framedrag;
    private javax.swing.JLabel framedrag1;
    private javax.swing.JLabel framedrag2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel x;
    private javax.swing.JLabel ㅡ1;
    private javax.swing.JLabel 강남;
    private javax.swing.JLabel 강동;
    private javax.swing.JLabel 강북;
    private javax.swing.JLabel 강서;
    private javax.swing.JLabel 관악;
    private javax.swing.JLabel 광진;
    private javax.swing.JLabel 구로;
    private javax.swing.JLabel 금천;
    private javax.swing.JLabel 노원;
    private javax.swing.JLabel 도봉;
    private javax.swing.JLabel 동대문;
    private javax.swing.JLabel 동작;
    private javax.swing.JLabel 마포;
    private javax.swing.JLabel 서대문;
    private javax.swing.JLabel 서초;
    private javax.swing.JLabel 성동;
    private javax.swing.JLabel 성북;
    private javax.swing.JLabel 송파;
    private javax.swing.JLabel 양천;
    private javax.swing.JLabel 영등포;
    private javax.swing.JLabel 용산;
    private javax.swing.JLabel 은평;
    private javax.swing.JLabel 종로;
    private javax.swing.JLabel 중;
    private javax.swing.JLabel 중랑;
    // End of variables declaration//GEN-END:variables
}
