/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algorithm;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.UnsupportedEncodingException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author PC
 */
public class thirdresult extends javax.swing.JFrame {
int xMouse;
int yMouse;
 public thirdresult (JFrame thirdresult) {
     
 }

 /**
     * Creates new form thirdresult
     */
    public thirdresult() {
         
        initComponents();
        
    } 

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        ㅡ1 = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        path = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        framedrag = new javax.swing.JLabel();
        priority_map = new javax.swing.JPanel();
        map = new javax.swing.JPanel();
        result_ta_scroll = new javax.swing.JScrollPane();
        result_ta = new javax.swing.JTextArea();
        panel = new javax.swing.JPanel();
        holder = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        topath = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ㅡ2 = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        ㅡ1.setBackground(new java.awt.Color(240, 233, 233));
        ㅡ1.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        ㅡ1.setForeground(new java.awt.Color(255, 255, 255));
        ㅡ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ㅡ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ㅡㅡㅡㅡ.gif"))); // NOI18N

        x.setBackground(new java.awt.Color(240, 233, 233));
        x.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        x.setForeground(new java.awt.Color(255, 255, 255));
        x.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/xx.gif"))); // NOI18N

        back.setText("x");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        path.setText("Path....");
        path.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pathMouseClicked(evt);
            }
        });
        path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/빨간하트.gif"))); // NOI18N
        jLabel3.setText("jLabel1");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        framedrag.setBackground(new java.awt.Color(255, 204, 204));
        framedrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                framedragMouseDragged(evt);
            }
        });
        framedrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                framedragMousePressed(evt);
            }
        });

        priority_map.setBackground(new java.awt.Color(255, 255, 255));

        map.setBackground(new java.awt.Color(255, 233, 233));

        result_ta_scroll.setBorder(null);

        result_ta.setBackground(new java.awt.Color(255, 233, 233));
        result_ta.setColumns(20);
        result_ta.setFont(new java.awt.Font("LG PC", 0, 18)); // NOI18N
        result_ta.setRows(5);
        result_ta_scroll.setViewportView(result_ta);

        javax.swing.GroupLayout mapLayout = new javax.swing.GroupLayout(map);
        map.setLayout(mapLayout);
        mapLayout.setHorizontalGroup(
            mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(result_ta_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        mapLayout.setVerticalGroup(
            mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(result_ta_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(null);

        holder.setOpaque(false);
        holder.setLayout(null);
        panel.add(holder);
        holder.setBounds(10, 30, 630, 480);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/jido.png"))); // NOI18N
        panel.add(jLabel4);
        jLabel4.setBounds(-10, -10, 670, 560);

        jPanel1.setBackground(new java.awt.Color(231, 205, 215));
        jPanel1.setLayout(null);

        topath.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        topath.setForeground(new java.awt.Color(255, 255, 255));
        topath.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topath.setText("VIEW PATHS");
        topath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                topathMouseClicked(evt);
            }
        });
        jPanel1.add(topath);
        topath.setBounds(0, 0, 510, 40);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        ㅡ2.setBackground(new java.awt.Color(240, 233, 233));
        ㅡ2.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        ㅡ2.setForeground(new java.awt.Color(255, 255, 255));
        ㅡ2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ㅡ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ㅡㅡㅡㅡ.gif"))); // NOI18N
        ㅡ2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ㅡ2MouseClicked(evt);
            }
        });
        jPanel3.add(ㅡ2);
        ㅡ2.setBounds(230, 10, 52, 52);

        x1.setBackground(new java.awt.Color(240, 233, 233));
        x1.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        x1.setForeground(new java.awt.Color(255, 255, 255));
        x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        x1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/xx.gif"))); // NOI18N
        x1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x1MouseClicked(evt);
            }
        });
        jPanel3.add(x1);
        x1.setBounds(290, 10, 52, 52);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setText("SEE THE PATH AND RECOMMEND");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(80, 30, 470, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/flower.gif"))); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(20, 10, 510, 100);

        javax.swing.GroupLayout priority_mapLayout = new javax.swing.GroupLayout(priority_map);
        priority_map.setLayout(priority_mapLayout);
        priority_mapLayout.setHorizontalGroup(
            priority_mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(priority_mapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(priority_mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(priority_mapLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(94, 94, 94)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(priority_mapLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(priority_mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(map, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        priority_mapLayout.setVerticalGroup(
            priority_mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(priority_mapLayout.createSequentialGroup()
                .addGroup(priority_mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(priority_mapLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(priority_mapLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(priority_mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(map, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(priority_map, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(framedrag, javax.swing.GroupLayout.DEFAULT_SIZE, 1304, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(priority_map, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(framedrag, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 671, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(1304, 733));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
 
    private void pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathActionPerformed

  
    secondlist sl = new secondlist();

   
   
    private void pathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pathMouseClicked
  
    }//GEN-LAST:event_pathMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        secondlist list = new secondlist();
        list.setVisible(true);
        list.pack();
        list.setLocationRelativeTo(null);
        list.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

     public static JLabel la1 = new JLabel();
    public static JLabel la2 = new JLabel();
    public static JLabel la3 = new JLabel();
    public static JLabel la4 = new JLabel();
    public static JLabel la5 = new JLabel();
    public static JLabel la6= new JLabel();
    public static JLabel la7 =  new JLabel();
    public static JLabel la8 = new JLabel();
    public static JLabel la9 = new JLabel();
    public static JLabel la10 = new JLabel();
   
    private void topathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topathMouseClicked
        // TODO add your handling code here:
         Graphics g = holder.getGraphics();
      String[] str = new String[sl.list_number()];
         str = sl.add_selected_third_result (); 
         for(int i=0;i<sl.list_number();i++){
             System.out.println(str[i]);
         }
          File file; 
          file = new File("textfile/distance_resultmap.txt");
          int count3=0;
           BufferedReader bufReader;
           
        try {
            bufReader = new BufferedReader(new InputStreamReader(new FileInputStream(file), "utf-8"));
             String line3 = "";
             String tmp3 = bufReader.readLine();
            String[] strlocal = new String[31];
             int[] strx = new int[31];
             int[] stry = new int[31];
             int x = 1, y = 1;
             int l=1;
         
               while((line3 = bufReader.readLine())!= null) { 
                  StringTokenizer st = new StringTokenizer(line3, "_");
                  while(st.hasMoreTokens()) {
                      if(count3 == 3) break;
                      
                      String temp3 = st.nextToken();
                     
                      if(count3== 0) {
                       strlocal[l] = temp3;
                       l++;
                      }
                      else if(count3 == 1) {
                          int fromx = Integer.parseInt(temp3);
                          strx[x] = fromx;
                          x++;
                          //x좌표
                      }
                      else if(count3==2) {
                          int fromy = Integer.parseInt(temp3);
                          stry[y] = fromy;
                          y++;
                          //y좌표
                      }
                      count3++;
                  }
                   count3 = 0;
               
              
               }  
               
                 //1부터 시작
                int[] linex = new int[sl.list_number()+1];
                int[] liney = new int[sl.list_number()+1];
                // 0 부터 시작
                for(int i=0;i<sl.list_number();i++){
                       for(int j=1;j<31;j++) {
                           if(str[i].equalsIgnoreCase(strlocal[j])) {
                              linex[i+1] = strx[j];
                              liney[i+1] = stry[j];     
                           }
                       }
                   }
                System.out.println("!!");
                 for(int i=1;i<=sl.list_number();i++){
                   System.out.println(linex[i] + ", " + liney[i]);
                }       
                 int panelnum=0;
                 for(int i=1;i<=sl.list_number();i++){
                          if(panelnum == 0){
                                 holder.add(la1);
                                  la1.setBounds(linex[i], liney[i], 20, 20);                             
                                  la1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/p1.png")));
                                  panelnum++;
                          }
                          
                          else if(panelnum == 1){
                                 holder.add(la2);
                                  la2.setBounds(linex[i], liney[i], 20, 20);
                                  la2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/p2.png")));
                                  panelnum++;
                          } 
                          else if(panelnum == 2){
                                 holder.add(la3);
                                  la3.setBounds(linex[i], liney[i], 20, 20);
                                  la3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/p3.png")));
                                  panelnum++;
                          }
                           else if(panelnum == 3){
                                 holder.add(la4);
                                  la4.setBounds(linex[i], liney[i], 20, 20);
                                  la4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/p4.png")));
                                  panelnum++;
                          }
                             else if(panelnum == 4){
                                 holder.add(la5);
                                  la5.setBounds(linex[i], liney[i], 20, 20);
                                  la5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/p5.png")));
                                  panelnum++;
                          } 
                            else if(panelnum == 5){
                                 holder.add(la6);
                                  la6.setBounds(linex[i], liney[i], 20, 20);
                                  la6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/p6.png")));
                                  panelnum++;
                          } 
                            else if(panelnum == 6){
                                 holder.add(la7);
                                  la7.setBounds(linex[i], liney[i], 20, 20);
                                  la7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/p7.png")));
                                  panelnum++;
                          } 
                          else if(panelnum == 7){
                                 holder.add(la8);
                                  la8.setBounds(linex[i], liney[i], 20, 20);
                                  la8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/p8.png")));
                                  panelnum++;
                          } 
                          else if(panelnum == 8){
                                 holder.add(la9);
                                  la9.setBounds(linex[i], liney[i], 20, 20);
                                  la9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/p9.png")));
                                  panelnum++;
                          } 
                          else if(panelnum == 9){
                                 holder.add(la10);
                                  la10.setBounds(linex[i], liney[i], 20, 20);
                                  la10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/p10.png")));
                                  panelnum++;
                          } 
                      
                        
                          
                          if(i!=sl.list_number()){
                          
                     g.drawLine(linex[i]+10, liney[i]+10, linex[i+1]+10, liney[i+1]+10);
                     }}
        
               
        } catch (FileNotFoundException ex) {
            Logger.getLogger(thirdresult.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(thirdresult.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(thirdresult.class.getName()).log(Level.SEVERE, null, ex);
        }
     
   
    
        System.out.println (sl.result_list());
      
     result_ta.setText(sl.result_list()+ "\n" +sl.result_recommend());
    }//GEN-LAST:event_topathMouseClicked

    private void framedragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedragMouseDragged
        int x = evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_framedragMouseDragged

    private void framedragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedragMousePressed
        xMouse = evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_framedragMousePressed

    private void ㅡ2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ㅡ2MouseClicked
this.setState(JFrame.ICONIFIED);
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_ㅡ2MouseClicked

    private void x1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_x1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(thirdresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(thirdresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(thirdresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(thirdresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new thirdresult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel framedrag;
    private javax.swing.JPanel holder;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel map;
    private javax.swing.JPanel panel;
    private javax.swing.JButton path;
    private javax.swing.JPanel priority_map;
    private javax.swing.JTextArea result_ta;
    private javax.swing.JScrollPane result_ta_scroll;
    private javax.swing.JLabel topath;
    private javax.swing.JLabel x;
    private javax.swing.JLabel x1;
    private javax.swing.JLabel ㅡ1;
    private javax.swing.JLabel ㅡ2;
    // End of variables declaration//GEN-END:variables
}
